### ISSUE TITLE
How do I set this up exactly?

### ISSUE THREAD

**Issue by h4rldev** [catppuccin/polybar#1]
The installation guide is quite unhelpful

Example:
What color goes where and whatnot

**Comment by nullishamy** [comment]
1) download your variant of choice from [here](https://github.com/catppuccin/polybar/tree/main/themes)
2) copy it to your config directory, normally `~/.config/polybar`
3) add the following to your `config.ini` polybar config:
```ini
[global/wm]
include-file = $HOME/.config/polybar/colors.ini
```
4) set your colours using the preset, something like:
```ini
[bar/top]
background=${colors.base}
border-color=${colors.crust}
border-size=4pt
font-0=Iosevka:size=13;2
foreground=${colors.surface0}
```

**Comment by justTOBBI** [comment]
Hey, there are plenty of examples of polybars on github if you just search up dotfiles.
I can guide you to https://github.com/justtobbi/dotfiles/tree/main :)

**Comment by brady0x48** [comment]
This is extremely late but colors like `base`, `mantle`, and `crust` are designed to be used as background colors. Obviously `text` and `subtext` are for text, and the generic colors such as `blue` and `yellow` are really up to you where you use them
