### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Hanuko33** [catppuccin/polybar#3]
`[global/wm]
include-file = $HOME/.config/polybar/mocha.ini`

After I put that in my config, an error started to appear:

`error: Uncaught exception, shutting down: /home/i3riced/.config/polybar/mocha.ini:7: Duplicate key name "base" defined in section "colors"`

**Comment by justTOBBI** [comment]
Would you be so kind to provide me your config file? (Not the color file from this repository)

**Comment by Hanuko33** [comment]
I don't know why, but it suddenly started working...
